/// Launcher icon variants available for user selection.
///
/// To add a new icon:
/// 1. Place preview/master PNGs under `assets/branding/`
/// 2. Add an [AppIconVariant] here
/// 3. Run `dart run scripts/sync_app_icons.dart`
/// 4. Commit generated native resources
///
/// Android default (`black`) reuses the existing `flutter_launcher_icons`
/// output (`@mipmap/ic_launcher`) — do not regenerate it.
class AppIconVariant {
  const AppIconVariant({
    required this.id,
    required this.label,
    required this.previewAsset,
    required this.androidMipmap,
    required this.backgroundColor,
    this.masterPath,
    this.reuseExistingAndroid = false,
    this.isDefault = false,
  });

  /// Stable id used in settings, backup, and native APIs.
  final String id;

  /// Short UI label (e.g. 黑底 / 白底).
  final String label;

  /// Flutter asset path for settings preview.
  final String previewAsset;

  /// Android `@mipmap/<name>` resource (no `@mipmap/` prefix).
  final String androidMipmap;

  /// Solid plate `#RRGGBB` for adaptive background (non-reuse variants).
  final String backgroundColor;

  /// Master PNG for iOS alternate / Android legacy mipmap when not reusing.
  final String? masterPath;

  /// When true, sync script must not touch Android resources for this id.
  final bool reuseExistingAndroid;

  final bool isDefault;
}

abstract final class AppIconCatalog {
  static const defaultId = 'black';

  /// Shared adaptive foreground (same as flutter_launcher_icons).
  static const adaptiveForegroundPath =
      'assets/branding/s1er_logo_transparent.png';

  /// Matches flutter_launcher_icons adaptive inset.
  static const adaptiveInsetPercent = 16;

  static const variants = <AppIconVariant>[
    AppIconVariant(
      id: 'black',
      label: '黑底',
      previewAsset: 'assets/branding/s1er_logo_black.png',
      androidMipmap: 'ic_launcher',
      backgroundColor: '#000000',
      reuseExistingAndroid: true,
      isDefault: true,
    ),
    AppIconVariant(
      id: 'white',
      label: '白底',
      previewAsset: 'assets/branding/s1er_logo_white.png',
      androidMipmap: 'ic_launcher_white',
      backgroundColor: '#FFFFFF',
      masterPath: 'assets/branding/s1er_logo_white.png',
    ),
  ];

  static AppIconVariant get defaultVariant =>
      variants.firstWhere((v) => v.isDefault, orElse: () => variants.first);

  static AppIconVariant? find(String? id) {
    if (id == null || id.isEmpty) return null;
    for (final v in variants) {
      if (v.id == id) return v;
    }
    return null;
  }

  /// Unknown / empty ids fall back to [defaultId].
  static String normalize(String? id) => find(id)?.id ?? defaultId;

  static bool contains(String? id) => find(id) != null;

  /// Non-default variants that need iOS alternate icon files / Android aliases.
  static Iterable<AppIconVariant> get alternateVariants =>
      variants.where((v) => !v.isDefault);

  /// Variants that need Android assets generated by the sync script.
  static Iterable<AppIconVariant> get androidGeneratedVariants =>
      variants.where((v) => !v.reuseExistingAndroid);
}
