# S1er — Pre-commit hook installer
#
# Installs a thin wrapper at .git/hooks/pre-commit that always runs
# scripts/pre-commit-hook.sh from the repo (edits take effect without
# reinstalling).
#
# Usage:
#   .\scripts\install_precommit.ps1
#
# Modes (env S1_PRECOMMIT — see scripts/pre-commit-hook.sh):
#   full (default) — format + analyze + test + M3
#   lite           — format + analyze only
#   skip           — bypass checks
#
# To uninstall, delete .git/hooks/pre-commit.

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$hookSource = Join-Path (Join-Path $repoRoot "scripts") "pre-commit-hook.sh"
$gitDir = Join-Path $repoRoot ".git"
$hooksDir = Join-Path $gitDir "hooks"
$hookDest = Join-Path $hooksDir "pre-commit"

if (-not (Test-Path $hookSource)) {
    Write-Error "Hook source not found: $hookSource"
    exit 1
}

if (-not (Test-Path $gitDir)) {
    Write-Error "No .git directory found. Are you in the repo root?"
    exit 1
}

if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

# Thin wrapper so updates to scripts/pre-commit-hook.sh apply immediately.
$wrapper = @"
#!/bin/sh
# Generated by scripts/install_precommit.ps1 - do not edit.
# Source of truth: scripts/pre-commit-hook.sh
ROOT="`$(git rev-parse --show-toplevel)"
exec sh "`$ROOT/scripts/pre-commit-hook.sh"

"@

# Write with LF line endings (Git for Windows sh expects Unix newlines).
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($hookDest, ($wrapper -replace "`r`n", "`n"), $utf8NoBom)

Write-Host "Pre-commit hook installed at: $hookDest"
Write-Host "Delegates to: $hookSource"
Write-Host ""
Write-Host "Default (S1_PRECOMMIT unset / full):"
Write-Host "  1. dart format"
Write-Host "  2. flutter analyze"
Write-Host "  3. flutter test"
Write-Host "  4. dart run scripts/audit_m3.dart"
Write-Host ""
Write-Host "Lite (small fixes):"
Write-Host '  $env:S1_PRECOMMIT="lite"; git commit -m "..."'
Write-Host ""
Write-Host "Skip entirely:"
Write-Host '  $env:S1_PRECOMMIT="skip"; git commit -m "..."'
Write-Host "  # or: git commit --no-verify"
Write-Host ""
Write-Host "If any check fails, the commit is rejected."
